apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - mountPath: /var/lib/mongodb/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mongo-pvc
