apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
spec:
  type: ClusterIP
  ports:
  - name: "order-service"
    port: 3002
    targetPort: 3002
  selector:
    app: order
