name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push front-end-react Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./front-end-react
          file: ./front-end-react/Dockerfile
          tags: |
            necati44/projet-cicd-front-end-react:latest
            necati44/projet-cicd-front-end-react:${{ github.sha }}

      - name: Build and Push order-service Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./order-service
          file: ./order-service/Dockerfile
          tags: |
            necati44/projet-cicd-order:latest
            necati44/projet-cicd-order:${{ github.sha }}

      - name: Build and Push user-service Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./user-service
          file: ./user-service/Dockerfile
          tags: |
            necati44/projet-cicd-user:latest
            necati44/projet-cicd-user:${{ github.sha }}
