name: Versioning Pipeline

on:
  push:
    branches:
      - '*.*.*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push front-end-react Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./front-end-react
        file: ./front-end-react/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/projet-cicd-front-end-react:${{ github.ref_name }}

    - name: Build and Push order-service Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./order-service
        file: ./order-service/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/projet-cicd-order:${{ github.ref_name }}

    - name: Build and Push user-service Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./user-service
        file: ./user-service/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/projet-cicd-user:${{ github.ref_name }}

